export const initialCategories = [
   "Liquor",
   "Shopping",
   "ATM Withdrawal",
   "Clothing",
   "Student Loan Payment",
   "Pay",
   "Insurance",
   "Utilities",
   "Dining",
   "Groceries",
   "Fuel",
   "Entertainment",
   "Healthcare",
   "Personal Care",
   "Travel",
   "Rent",
   "Car Wash",
   "TV",
   "Internet",
   "Phone",
   "Credit Card Payment",
   "Gambling",
   "Home Improvement",
   "Money Transfer",
   "Subscription",
   "Gift",
   "Other",
   "Vehicle Payment",
];
